district:
  label: Район
  type: text
  showOnCard: true
address:
  label: Адрес
  type: text
  showOnCard: true
currency:
  label: Валюта
  type: text
  showOnCard: true
bookingLinks:
  label: Бронирование
  type: links
  showOnCard: true
